apiVersion: v1
kind: Pod
metadata:
    name: webapp
    labels:
        app: webapp
        release: "0"
spec:
    containers:
        -   name: webapp
            image: richardcherterwood/k8s-fleetman-weapp-angular:release0

---

apiVersion: v1
kind: Pod
metadata:
    name: webapp
    labels:
        app: webapp
        release: "0.5"
spec:
    containers:
        -   name: webapp
            image: richardcherterwood/k8s-fleetman-weapp-angular:release0.5


