apiVersion: v1
kind: Service
metadata:
    name: fleetman-webapp
spec:
    selector:
        app: webapp
        release: "0"
    ports:
        -   name: http
            port: 80
            nodePort: 300080
    type: NodePort
