apiVersion: v1
kind: Service
metadata:
    name: fleetman-webapp
spec:
    selector:
        app: webapp
    ports:
        -   name: http
            port: 80
            nodePort: 300080
    type: NodePort
---

apiVersion: v1
kind: Service
metadata:
    name: fleetman-queue
spec:
    selector:
        app: queue
    ports:
        - name: http
          port: 8161
          nodePort: 30010
        - name: endpoint
          port: 61616

    type: NodePort
