apiVersion: v1
kind: Service
metadata:
    name: fleetman-queue
spec:
    selector:
        app: queue
    ports:
        -   name: http
            port: 8161
            nodePort: 300010
    type: NodePort
